# Configuration for ML project

data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  train_test_split: 0.2
  random_state: 42

model:
  type: "random_forest"
  params:
    n_estimators: 100
    max_depth: 10
    random_state: 42

training:
  cv_folds: 5
  scoring: "accuracy"
  
features:
  numerical: []
  categorical: []
  target: ""

output:
  model_path: "models/model.pkl"
  figures_path: "reports/figures"
